export {default as HTML5} from "@react/icons/HTML5"
export {default as CSS3} from "@react/icons/CSS3"
export {default as SASS} from "@react/icons/SASS"
export {default as Javascript} from "@react/icons/Javascript"
export {default as Tailwind} from "@react/icons/Tailwind"
export {default as Git} from "@react/icons/Git"
export {default as React} from "@react/icons/React"
export {default as ChatGPT} from "@react/icons/ChatGPT"
export {default as AstroJs} from "@react/icons/AstroJs";
export {default as Github} from "@react/icons/Github";
export {default as Linkedin} from "@react/icons/Linkedin";
export {default as X} from "@react/icons/X";
export {default as Tiktok} from "@react/icons/Tiktok";
export {default as Netlify} from "@react/icons/Netlify";
export {default as Sun} from "@react/icons/Sun";
export {default as Moon} from "@react/icons/Moon"